#!/usr/bin/env bash
#sudo 
sudo apt-get update
sudo apt-get install -y nginx
sudo rm /var/www/html/index.nginx-debian.html
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx start
echo "Nginx has been installed and is running."
