#!/usr/bin/env bash
# inst

sudo apt-get -y update
sudo apt-get -y install nginx
echo "HOlla u r in lujain web yay" | sudo tee /var/www/html/index.html
echo "
server {
        listen 80 default_server;
        listen [::]:80 default_server;


        root /var/www/html;

        # index
        index index.html index.htm index.nginx-debian.html;

        server_name lujaindom.tech;

        location /redirect_me {
                return 301 https://www.nginx.com/blog/creating-nginx-rewrite-rules/;
        }
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
