#!/usr/bin/env bash
# Ins

# Update the package lists for upgrades and new package installations
sudo apt-get update

# Ins
sudo apt-get install -y nginx

# Write
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Write
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html > /dev/null

# Define the Nginx configuration
CONFIG="
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name ajwadg.tech;

        error_page 404 /error_404.html;

        location = /error_404.html {
                root /var/www/html;
                internal;
        }

        location /redirect_me {
                return 301 https://www.nginx.com/blog/creating-nginx-rewrite-rules/;
        }
}"

# Write
echo "$CONFIG" | sudo tee /etc/nginx/sites-available/default

# Res
sudo service nginx restart
