#!/usr/bin/env bash
#good work its ok lujain

sudo apt-get -y update
sudo apt-get -y install nginx

name=$(hostname)

echo "Hello World!" > /var/www/index.html
echo "Ceci n'est pas une page" > /var/www/error_404.html
con="server {
    listen 80 default_server;
    listen [::]:80 default_server;

    add_header X-Served-By $name always;

    root /var/www;
    index index.html;

    server_name lujaindom.tech;

    error_page 404 /error_404.html;

    location = /error_404.html {
        root /var/www;
        internal;
    }

    location /redirect_me {
        return 301 https://www.nginx.com/blog/creating-nginx-rewrite-rules/;
    }
}"

echo "$con" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
