#!/usr/bin/env bash
#installing
sudo apt-get -y update
sudo apt-get -y install nginx
name=$(hostname)
echo "<h1>HollA HOLLA HOLAA $name</h1>" > /var/www/index.html
echo "<h1>there is error babe</h1>" > /var/www/error_404.html
con="server {
    listen 80 default_server;
    listen [::]:80 default_server;

    add_header X-Served-By $name always;

    root /var/www;
    index index.html;

    server_name lujainb.tech;

    error_page 404 /error_404.html;

    location = /error_404.html {
        root /var/www;
        internal;
    }

    location /redirect_me {
        return 301 https://www.nginx.com/blog/creating-nginx-rewrite-rules/;
    }
}"
echo "$con" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
