#!/usr/bin/env bash
#i am good today

sudo apt-get -y update
sudo apt-get -y install haproxy

echo "
frontend www
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 483444-web-01 52.87.26.114 check
    server 483444-web-02 100.25.103.128 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
