#!/usr/bin/env bash
# haproxy
sudo apt-get -y update
sudo apt-get -y install haproxy
echo "
frontend www
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 483444-web-01 54.236.53.177 check
    server 483444-web-02 52.201.211.59 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
