#!/usr/bin/env bash
#print best scoll untill 8 than print good luck and continue

j=0
while [ $j -le 9 ]
do
	if [ $j -eq 3 ]; then
		echo "bad luck"
	elif [ $j -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi

	j=$((j + 1))
done
