#!/usr/bin/env bash
#print best scoll untill 4 than print bad luck from China and continue

j=1
while [ $j -le 20 ]
do
	case $j in
		4)
			echo "$j"
			echo "bad luck from China"
			;;
		9)
			echo "$j"
			echo "and then bad luck from Japan"
                        ;;
		17)
			echo "$j"
			echo "and then bad luck from Italy"
                        ;;
		*)
			echo $j
			;;
	esac

	j=$((j + 1))
done
